// router/link-list.js
export const linksList = [
  {
    title: "docs",
    caption: "quasar_dev",
    icon: "las la-graduation-cap",
    link: "https://quasar.dev",
    authentication: false,
  },
  {
    title: "newValidator",
    caption: "new_page_for_the_certifier_validator",
    icon: "las la-certificate",
    link: "NewValidadorPage",
    authentication: false,
  },
  {
    title: "pdf_viewer",
    caption: "pdf_viewer_caption",
    icon: "las la-file-pdf",
    link: "PdfViewerPage",
    authentication: true,
  },
  {
    title: "graphic",
    caption: "graphic_caption",
    icon: "las la-chart-bar",
    link: "GraphicPage",
    authentication: true,
  },
  {
    title: "Users",
    caption: "table_user",
    icon: "las la-user",
    link: "UserPage",
    authentication: true,
  },
  {
    title: "Organisms",
    caption: "table_organisms",
    icon: "las la-sitemap",
    link: "OrganismsPage",
    authentication: true,
  },
  {
    title: "Calendar",
    caption: "calendar_page",
    icon: "las la-calendar",
    link: "CalendarPage",
    authentication: true,
  },
  {
    title: "Maps",
    caption: "map_page",
    icon: "las la-map",
    link: "MapPage",
    authentication: true,
  },
  {
    title: "Products",
    caption: "products_page",
    icon: "las la-store-alt",
    link: "ProductsPage",
    authentication: true,
  },
];
